### ISSUE TITLE
motivation_dataset

### ISSUE THREAD

**Issue by Bernard-Yang** [Joanna0123/character_profiling#1]
请问motivation_dataset.json的具体构造过程是怎样的，例如使用 gpt4 产生MCQ 的 prompt可否分享？谢谢！

**Comment by Joanna0123** [comment]
你好！用于构造MR MCQs的prompt已经更新在`code\prompts\construct_mr_mcqs\prompt.txt`了，具体构造过程及后续筛选标准可以参考文中Section 4.3和Appendix E.3的部分。
